services:
    api.file_uploader:
        class: ApiBundle\Service\FileUploader
        arguments: ['%image_directory%']
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
